name: Run Tests and SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [video-upload-service, video-processing-service]

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio httpx flake8 black

      - name: Run tests
        run: |
          PYTHONPATH=. pytest --disable-warnings --cov=app --cov-report=xml:coverage.xml

      #- name: Lint with flake8
      #  run: flake8 app --max-line-length=88

      #- name: Check formatting with black
      #  run: black --check app

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: ${{ matrix.service }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


