name: Test and Analyze

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: videodb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: auth-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx[http2] pytest-asyncio

      - name: Run tests with coverage
        working-directory: auth-service
        run: |
          pytest --disable-warnings --cov=app --cov-report=xml:coverage.xml

      - name: Lint code with flake8
        working-directory: auth-service
        run: |
          pip install flake8
          flake8 app --max-line-length=88

      - name: Check formatting with black
        working-directory: auth-service
        run: |
          pip install black
          black --check app

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: auth-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
